### ISSUE TITLE
What does `ll` mean?

### ISSUE THREAD

**Issue by nclskfm** [MSLars/German-Text-Simplification#1]
Hello, I'm curious about what `ll` in the training example means. I can't find it explained in the documentation or in the paper.

If I need to guess, I would say something like Linguistic Level. But maybe you can explain it further.

Thanks @MSLars 🚀

**Comment by MSLars** [comment]
Your suggestion is correct. `ll` is short for "language level". During development, we thought it might be helpful to tell the model in which style it should simplify. We did not use the information in this version, but will in our next iteration.
